### Registrar novo usuário (adopter padrão)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "João Silva2",
  "email": "joao@example2.com",
  "password": "senha123",
  "phone": "11999999999"
}

###

### Registrar novo usuário (admin)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Maria Admin",
  "email": "maria@email.com",
  "password": "senha123",
  "phone": "11999999999",
  "role": "admin"
}

###

### Login usuário adopter
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joao@example.com",
  "password": "novaSenha123a"
}

###

### Login usuário admin
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "maria@email.com",
  "password": "senha123"
}

###

### Definir token manualmente para testes
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2FvQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkb3B0ZXIiLCJpYXQiOjE3NTEzMTEwNDIsImV4cCI6MTc1MTMxNDY0Mn0.Z497NyAMuEJI69Nk3h0fa-DtMVC_9N5X9SPJEDhAwlQ

### 👤 Listar todos os usuários (admin)
GET http://localhost:3000/users
Authorization: Bearer {{token}}

###

### 👤 Obter usuário por ID (admin ou o próprio)
GET http://localhost:3000/users/3
Authorization: Bearer {{token}}

###

### 👤 Atualizar usuário (admin ou o próprio)
PUT http://localhost:3000/users/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "João",
  "email": "joao@example.com",
  "password": "novaSenha123a",
  "phone": "11988888888"
}

###

### 👤 Deletar usuário (apenas admin)
DELETE http://localhost:3000/users/6
Authorization: Bearer {{token}}

###